ALTER TABLE sfemployee ADD PROPERTY_COUNT INT DEFAULT 0;

CREATE OR REPLACE TRIGGER update_property_count
AFTER INSERT ON property
FOR EACH ROW
BEGIN
  UPDATE sfemployee
  SET PROPERTY_COUNT = PROPERTY_COUNT + 1
  WHERE ID = :new.SUPERVISORID;
END;

ALTER TABLE sfemployee
ADD CONSTRAINT check_property_count
CHECK (PROPERTY_COUNT <= 3);
